export const actionType = {
    START_FETCH_LIST_OF_MOVIE: "START_FETCH_LIST_OF_MOVIE",
    FINISH_FETCH_LIST_OF_MOVIE: "_FETCH_LIST_OF_MOVIE",
    START_FETCH_LIST_OF_FREE_MOVIE: "START_FETCH_LIST_OF_FREE_MOVIE",
    FINISH_FETCH_LIST_OF_FREE_MOVIE: "FINISH_FETCH_LIST_OF_FREE_MOVIE",
    ERROR_FETCH_DATA:"ERROR_FETCH_DATA"
}