export const actionType = {
    START_FETCH_LIST_OF_MOVIE: "START_FETCH_LIST_OF_MOVIE",
    FINISH_FETCH_LIST_OF_MOVIE: "_FETCH_LIST_OF_MOVIE",

    START_FETCH_LIST_OF_FREE_MOVIE: "START_FETCH_LIST_OF_FREE_MOVIE",
    FINISH_FETCH_LIST_OF_FREE_MOVIE: "FINISH_FETCH_LIST_OF_FREE_MOVIE",

    START_FETCH_DETAIL_OF_MOVIE:"START_FETCH_DETAIL_OF_MOVIE",
    FINISH_FETCH_DETAIL_OF_MOVIE:"FINISH _FETCH_DETAIL_OF_MOVIE",

    UPDATE_STATE_OF_IMAGE_URL:"UPDATE_STATE_OF_IMAGE_URL",

    UPDATE_KEYWORD:"UPDATE_KEYWORD",

    UPDATE_TOP_CAST:"UPDATE_TOP_CAST",

    UPDATE_REVIEWS:"UPDATE_REVIEWS",

    GET_IMAGE:"GET_IMAGE",

    UPDATE_RECOMMAND:"UPDATE_RECOMMAND",

    GET_SEARCH:"GET_SEARCH",

    ERROR_FETCH_DATA:"ERROR_FETCH_DATA"
}